### ISSUE TITLE
Installer Not working

### ISSUE THREAD

**Issue by Jonah0037** [DavidJClark/phpVMS-3#1]
I can't get the installer to work. it says that the page I requested was not found.

**Comment by Jonah0037** [comment]
And i got the new update too.

**Comment by DavidJClark** [comment]
I believe that this request is not for phpVMS 3. Please refer to the forum for support of older versions. https://forum.phpvms.net

**Comment by DavidJClark** [comment]
The installer has not been uploaded at this time. What is this page from?

**Comment by Jonah0037** [comment]
Phpvms3..If that is what your asking for.
